### ISSUE TITLE
crash when leaving meeting

### ISSUE THREAD

**Issue by gmoens-vuzix** [webex/webex-android-sdk#83]
Starting happening after upgrading to SDK 3.0. When you leave a meeting, sometimes there will be a JNI crash. It seems to depend on the interaction the user has with the app. In particular, the following steps seem to trigger the crash.

1. Join a meeting
2. Stop video
3. Start video
4. Do something that causes Call.setVideoRenderViews(videoRenderViews) to be called
5. Leave meeting or have the remote side hang up
6. Crash

The kitchen sink app doesn't have a way to do step 4, so I have not been able to recreate the crash in that app.

In our app, we have a way that you can swap the incoming and outgoing videos so they change places, this is what calls setVideoRenderViews(). We can also navigate to another screen that has separate VideoRenderViews and this also causes the crash when you leave. This would seem to indicate some kind of leak related to VideoRenderViews and having multiple of them in your app that get switched between. These views are not getting cleaned up properly when the meetings ends.

I've attached the crash log.

[webex_leave_meeting_crash.txt](https://github.com/webex/webex-android-sdk/files/6879730/webex_leave_meeting_crash.txt)

**Comment by ankbat** [comment]
@gmoens-vuzix 
In your application, when you do swap, do you provide new surface views and swap it to new locations? OR use old surface view references?

**Comment by ankbat** [comment]
@gmoens-vuzix  
Can you also please provide full logs?
You can use our [API](https://webex.github.io/webex-android-sdk/com.ciscowebex.androidsdk/-webex/getlog-file-uri.html), it will give you zip URI to download or send it through email.

**Comment by gmoens-vuzix** [comment]
@ankbat
When swap occurs, we tear down the existing fragment that's on screen and create a new one. So the VideoRenderViews are new, we don't reuse the old ones. If we navigate to a new screen and come back, we reuse the old views.

**Comment by ankibatr** [comment]
@gmoens-vuzix 
Try below snapshot version and test your scenarios. This snapshot version only contains ARM64 architecture. It will work only on physical device not on emulator.

1. Add the following repository to your top-level build.gradle file:
`allprojects {
    repositories {
        maven {
            url 'https://devhub.cisco.com/artifactory/webexsdk-SNAPSHOT/'
        }
    }
}`
 
2. Add the webex-android-sdk library as a dependency for your app in the build.gradle file:
`dependencies {
    implementation 'com.ciscowebex:androidsdk:3.1.0.2-SNAPSHOT@aar'
}`

**Comment by gmoens-vuzix** [comment]
@ankibatr
I upgraded to 3.1.0 and still saw the crash. Then I upgraded to the snapshot you provided and now the crash happens less frequently. Instead of every time, maybe every other time?

[webex_leave_meeting_crash_8_23.txt](https://github.com/webex/webex-android-sdk/files/7034705/webex_leave_meeting_crash_8_23.txt)

I noticed the crash looks slightly different now. It used to be:

JNI ERROR (app bug): accessed deleted Global 0x2a26

Now it is:

JNI ERROR (app bug): attempt to use stale Global 0x2a82 (should be 0x2a86)

**Comment by ankibatr** [comment]
@gmoens-vuzix 
Thanks for testing and sharing new logs. I will have a look and will update you.

**Comment by gmoens-vuzix** [comment]
@ankibatr 
I reverted back to production 3.1.0 and tried your audio only scenario. I was still able to reproduce the crash if I left the main call screen (view participant list for example) and returned to it a few times. Each time you return to the call screen, new video render views are created and passed into setVideoRenderViews(). What I said before about us reusing video render views did not appear to be true. We always create new ones.

If I disable this behavior and allow the old video render views to be reused, the crash is avoided. In this case, our app only calls setVideoRenderViews() once for the duration of the call. The less times you call this method, the less likely the crash happens. However, as soon as you start turning video on and off and swapping the videos, setVideoRenderViews() will get called multiple times.

**Comment by ankibatr** [comment]
@gmoens-vuzix 
Thanks for the test. Can you please test audio only scenario with snapshot version which I released?
I did some changes in snapshot version related to setVideoRenderViews API. I want to test your scenario for audio only and then switching to video in between of call.
**3.1.0.2-SNAPSHOT@aar**

**Comment by gmoens-vuzix** [comment]
@ankibatr
Using 3.1.0.2-SNAPSHOT, I can't get it to crash with audio only calls. After adding videos to those audio only calls, I still can't make it crash. Even with video calls from the start, I'm having difficulty recreating the crash after multiple attempts.

Downgrading back to 3.1.0 and the crash returns when you exit the meeting, first try. So your changes have definitely helped!

**Comment by ankibatr** [comment]
@gmoens-vuzix 
Thanks for confirming. We will release this solution in 3.2 version.
